### ISSUE TITLE
Sum of consumptions for one account

### ISSUE THREAD

**Issue by matthieu-gendreau** [bobar/tdfb#17]
Feature of the old TDB

**Comment by tdeo** [comment]
https://github.com/bobar/tdfb/commit/1b75d138c0894e68afe450e307e0b7e1ba701128: <img width="577" alt="screen shot 2017-03-25 at 12 00 01" src="https://cloud.githubusercontent.com/assets/6230277/24321676/9b85b014-1152-11e7-90b7-a8ed22a909f3.png">
