### ISSUE TITLE
Bank font-size is too big

### ISSUE THREAD

**Issue by matthieu-gendreau** [bobar/tdfb#18]
Easy to see with slate theme.
When hovering "Group log" the element doesn't fill the height of the navbar.

![screenshot from 2017-03-25 13-35-22](https://cloud.githubusercontent.com/assets/5287429/24324616/eeca8bfc-115f-11e7-9dbd-4c9cfda8e591.png)

**Comment by tdeo** [comment]
Fixed https://github.com/bobar/tdfb/commit/9013ef89078ab68a4832d77436d034defd8dab98
