### ISSUE TITLE
Implement TDB menu features

### ISSUE THREAD

**Issue by tdeo** [bobar/tdfb#23]
![image](https://cloud.githubusercontent.com/assets/6230277/24402189/bb1abc3c-13b7-11e7-83c5-e333afae19ff.png)

- [ ] Sum account balances (Should be eventually solved using MySQL transactions)
- [x] See binets
- [x] See accounts (with filtering options) -> and export them
- [x] Log from CSV file
- [ ] Reset turnovers
- [x] ~Reset history~ (not needed now that we have pagination)

**Comment by matthieu-gendreau** [comment]
Reset turnovers?

**Comment by tdeo** [comment]
Turnover is "Euros depenses depuis dernier reset". It's stored in accounts.turnover to be fetched effectively instead of going through all transactions

**Comment by matthieu-gendreau** [comment]
See binets: https://github.com/bobar/tdfb/commit/c0d75a26b1c542de2d2fd3370cf69597cb0b9206

**Comment by matthieu-gendreau** [comment]
For CSV files, is it possible to get samples ?
I think we should support excel too, it would be nice

**Comment by tdeo** [comment]
Well, Excel knows how to open CSV files in the first place... I'm not sure it's worth the trouble (maybe ask Jean ?). I'll try to get some samples.

**Comment by matthieu-gendreau** [comment]
I think it is easy enough for us to recognize the extension (CSV, XLS, XLSX) and do CSV.open or XLS.open ?

**Comment by matthieu-gendreau** [comment]
You deal with CSV file or do you want me to take care of it ?

**Comment by tdeo** [comment]
File import implemented with https://github.com/bobar/tdfb/commit/613cf3a62f60257dcbb10af0b5bcd25e419ec403 and https://github.com/bobar/tdfb/commit/81ee523235381ef3cc4a432836bf7cfb0e75080c

**Comment by matthieu-gendreau** [comment]
I think we can skip the two last options or relabel them as enhancement and not core features since they have not been used for years. 
Thus we should close this issue. Good job on the import.
