### ISSUE TITLE
Implement cancellation mechanism

### ISSUE THREAD

**Issue by tdeo** [bobar/tdfb#24]
This is actually a bit tricky:

Today's behaviour is to be able to cancel everything since the account was opened, and delete the entry in transactions, all without authentication.

**Comment by matthieu-gendreau** [comment]
So it won't be very hard to to better ? :)

**Comment by matthieu-gendreau** [comment]
Maybe we can :

- Cancel without authentication during 10 minutes, with after

- Instead of delete, we log the opposite operation with the references in the comment ("Cancelling transaction #234543")

**Comment by tdeo** [comment]
It's not as straightforward:
- right now, `transactions` don't have any PK, or FK. It used too, but that was causing "ghost" transactions not being written with the amount being taken from the account (If 2 transactions for the same account in the same second). Removing the PK solved it back in the time.
```mysql
CREATE TABLE `transactions` (
  `id` int(11) DEFAULT NULL,
  `price` int(11) DEFAULT NULL,
  `comment` text,
  `admin` int(11) DEFAULT NULL,
  `id2` int(11) DEFAULT NULL,
  `date` datetime DEFAULT NULL,
  KEY `id_date` (`id`,`date`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 |
```

I like the idea of a delay to cancel without authentication, but I guess it should be **way** shorter (maybe 30 seconds?).

I think eventually, we'll want to redesign a ~bit~ lot the schema of this table. But for now, for compatibility reasons, we should stick to something compatible, either logging the opposite, or updating the transaction to have a value of 0 and append a comment saying "Cancelled, was 2 euros" or something.

**Comment by tdeo** [comment]
https://github.com/bobar/tdfb/commit/c14526d0ce56b543dc7e041fe8be24e4c5c37bd6
