### ISSUE TITLE
On error 400, print response message instead of the default one

### ISSUE THREAD

**Issue by matthieu-gendreau** [bobar/tdfb#26]

**Comment by matthieu-gendreau** [comment]
Use case: if you try to delete the BôBarman rights (very stupid), the message is " Something went wrong, call the SIE." but the request response is "Those rights are in use"

**Comment by matthieu-gendreau** [comment]
https://github.com/bobar/tdfb/commit/1ae8811a95deed29ff1ca7e0f606abd760d1b62b

**Comment by tdeo** [comment]
👍
