### ISSUE TITLE
Import frankiz

### ISSUE THREAD

**Issue by tdeo** [bobar/tdfb#34]
When crawling the 2016, Arthur MIGLIORINI is not imported? Or at least not linked ?

From: Gendral <>

**Comment by tdeo** [comment]
Linking existing accounts to a frankiz user is not automated, but the rake task `frankiz:associate_accounts` does it.

**Comment by matthieu-gendreau** [comment]
Du il faudrait un bouton pour les fiston ? Ou le lancer après chaque import
?

**Comment by matthieu-gendreau** [comment]
I reopened it maybe it is not properly worded but it is a real problem for the fistons

**Comment by tdeo** [comment]
Actually it's been a problem only because I broke account creation (https://github.com/bobar/tdfb/issues/37) and I guessed they created accounts manually from the old software. But it shouldn't be happening

**Comment by tdeo** [comment]
I re-associated all accounts for promo 2016 to the proper frankiz users.

**Comment by matthieu-gendreau** [comment]
Ok thanks.
What would happen now if an account is created with the Java TDB ?
I assume that it will happen again ?

**Comment by tdeo** [comment]
Of course, the old one doesn't support any Fkz-related features. They shouldn't use it.

**Comment by matthieu-gendreau** [comment]
Then we should delete the functionnality from the old frankiz or this problem will reoccur.
Do you agree?

**Comment by matthieu-gendreau** [comment]
Maybe a bit too radical

**Comment by tdeo** [comment]
Well, just convince them to stop using the old one (or remove it from the computer)

**Comment by matthieu-gendreau** [comment]
Well, it is not going to happen for now

**Comment by tdeo** [comment]
Anyway, closing this, frankiz import works properly

**Comment by matthieu-gendreau** [comment]
Should I open an issue to allow them to link an existing trigramme to a frankiz entry ?

**Comment by tdeo** [comment]
Maybe we can add a page to do so.
