### ISSUE TITLE
Issue in cider logging

### ISSUE THREAD

**Issue by tdeo** [bobar/tdfb#43]
When logging a cider 2.2 €, the "TDB" logs it into 2.21 € : I think it is dishonest to do that to our customers. Also, 4.4 is logged into 4.41.
Have a nice day !

From: Hoorelbeke <>

**Comment by matthieu-gendreau** [comment]
https://github.com/bobar/tdfb/blob/master/app/models/transaction.rb#L15

(byebug) amount
2.2
(byebug) (amount * 100)
220.00000000000003
(byebug) (amount * 100).ceil
221

**Comment by tdeo** [comment]
Damn floating point numbers.

The idea is that if you log 2.223, we want to take 2.23 and not 2.22, anyway https://github.com/bobar/tdfb/commit/060b3e5488e2bcfdd249df5acf773637b81ca11a should account for the epsilon part.
