### ISSUE TITLE
Fix the app creating double issues

### ISSUE THREAD

**Issue by tdeo** [bobar/tdfb#50]
It's quite annoying

**Comment by matthieu-gendreau** [comment]
Can you confirm it is no more connected to zapier ?

**Comment by tdeo** [comment]
Well, it's not sending mails anymore...

**Comment by tdeo** [comment]
This was actually due to prod's auth mechanism, fixed by https://github.com/bobar/tdfb/commit/4e09542235d34c213d72ebcae8cb62a0ef363a4f
