### ISSUE TITLE
Page d'accueil TDB

### ISSUE THREAD

**Issue by lebobar** [bobar/tdfb#57]
Coucou !
Si possible ça serait cool que les trigrammes des meilleurs consommateurs sur la page d'accueil soit cliquables pour y acceder directement ! 
Bisous du BôB 15 qui rouvre, on s'voit à la pass

Name: Jean et Robin
Email: bobar@binets.polytechnique.fr

**Comment by matthieu-gendreau** [comment]
https://github.com/bobar/tdfb/commit/4da04ee397e055027936c8a5b7b767de50a6e787

**Comment by matthieu-gendreau** [comment]
@tdeo can you deploy it? (I forgot how to deploy ...)

**Comment by tdeo** [comment]
Just rolled out.
