### ISSUE TITLE
Compte étrange dans les meilleurs consommateurs des 7 derniers jours

### ISSUE THREAD

**Issue by lebobar** [bobar/tdfb#59]
Salut les gars, je sais pas pourquoi mais j'ai l'impression que l'affichage des meilleurs consommateurs de la semaine déconne complètement. Y'a un trigramme qui s'appelle "0" et qui a consommé exactement 100€, tandis que les consommations des autres trigrammes ont pas l'air de se mettre à jour ! 
La bise !

Name: Sauvignon
Email: jean.sauvignon@polytechnique.edu

**Comment by tdeo** [comment]
Can't reproduce.
